DL-14483: Scottish journey changes in benefits content, unit tests modifications
hmrc/childcare-calculator-frontend pull request #688
Opened 2024-09-23 22:41 UTC by upasanasingh-hmrc

# JIRA Story or Github Number - descriptive title

**Bug fix / New feature** (delete as appropriate)

Please include a summary / description of the change and which issue it fixes.  Include any relevant user needs, context or links to other PRs related to this PR (eg. acceptance tests, environment config).

## Checklist

 - [ ]  I've made every effort to commit high quality, clean code and I have executed relevant static analyses to be sure
 - [ ]  I've included appropriate tests with any code I've added (Unit, Integration, Acceptance etc.)
 - [ ]  I've executed the acceptance test pack locally to ensure there are no functional regressions
 - [ ]  I've added my code using logical, atomic commits, squashing as appropriate - including the JIRA issue number in the commit message
 - [ ]  I've run a dependency check to ensure all dependencies are up to date

2024-09-24 13:41 UTC, pankaj2453 requested changes

2024-09-24 13:41 UTC, pankaj2453 commented on app/uk/gov/hmrc/childcarecalculatorfrontend/views/partnerAnyTheseBenefitsCY.scala.html
> +                    <li>@messages("partnerAnyTheseBenefitsCY.li.carers")</li>
here, no need of case, just if/else for last  li

2024-09-24 13:41 UTC, pankaj2453 commented on app/uk/gov/hmrc/childcarecalculatorfrontend/views/doYouOrYourPartnerGetAnyBenefits.scala.html
> +                <li>@messages("doYouOrYourPartnerGetAnyBenefits.li.carersAllowance")</li>
here, no need of case, just if/else for 1st li

2024-09-24 13:41 UTC, pankaj2453 commented on app/uk/gov/hmrc/childcarecalculatorfrontend/views/doYouGetAnyBenefits.scala.html
> +@bulletList = @{location match {
instead of case, just add specific message to seq based on location.

2024-09-24 13:41 UTC, pankaj2453 commented on app/uk/gov/hmrc/childcarecalculatorfrontend/views/partnerAnyTheseBenefitsPY.scala.html
> +            }}
as previous comment

2024-09-24 13:41 UTC, pankaj2453 commented on app/uk/gov/hmrc/childcarecalculatorfrontend/views/youAnyTheseBenefitsCY.scala.html
> +
as previous comment

2024-09-24 13:41 UTC, pankaj2453 commented on app/uk/gov/hmrc/childcarecalculatorfrontend/views/youAnyTheseBenefitsPY.scala.html
> +        }
as previous comment

2024-09-24 15:07 UTC, DivyaManimaran-hmrc commented on app/uk/gov/hmrc/childcarecalculatorfrontend/models/integration/Claimant.scala
> +        case `scottishCarersAllowanceBenefits` => benefits.copy(carersAllowance = true)
should it not be scottishCarersAllowance = true ?

2024-09-26 12:48 UTC, upasanasingh-hmrc commented on app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/PartnerAnyTheseBenefitsCYController.scala
> +        val isScotland = userAnswers.location.contains(Location.SCOTLAND)
Empty location check is present in onSubmit method already before validate method is called. Changed it to use equals now

2024-09-29 22:18 UTC, upasanasingh-hmrc commented on app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/YouAnyTheseBenefitsCYController.scala
> +        val isScotland = userAnswers.location.contains(Location.SCOTLAND)
Corrected

2024-10-01 15:18 UTC, merged